### ISSUE TITLE
Add support for generating source map

### ISSUE THREAD

**Issue by jirutka** [Mogztter/opal-node-compiler#6]
The Ruby version of Opal supports source maps:

```rb
require 'opal'

builder = Opal::Builder.new
builder.append_paths 'lib'
builder.build 'path/to/entrypoint'

code = builder.to_s
source_map = builder.source_map
```

opal-node-compiler does not expose source map and accessing it directly results in error:

```js
const { Builder: OpalBuilder } = require('opal-compiler')

const builder = OpalBuilder.create()
builder.appendPaths('lib')

const code = builder.build(modulePath).toString()
const sourceMap = builder.$source_map()
```
```
SourceMap: uninitialized constant Opal::SourceMap
    at Function.$$const_missing (node_modules/opal-runtime/src/opal.js:3052:52)
    at const_missing (node_modules/opal-runtime/src/opal.js:224:32)
    at Opal.const_get_qualified (node_modules/opal-runtime/src/opal.js:271:38)
    at constructor.$$source_map (node_modules/opal-compiler/src/opal-builder.js:1988:20)
```

**Comment by Mogztter** [comment]
I think we need to explicitly require the SourceMap module:

https://github.com/opal/opal/blob/cba2fea2cea7c461bf22ab30a491064113c78a78/lib/opal/builder.rb#L124

**Comment by Mogztter** [comment]
It should be fixed in https://github.com/Mogztter/opal-node-compiler/pull/10
